### ISSUE TITLE
[LDAP] User without uid attribute can not login (after upgrade to 6.7)

### ISSUE THREAD

**Issue by favadi** [gitlabhq/gitlabhq#6652]
With gitlab 6.6, we can login without problem with user that does not have a `uid` attribute. After upgrade to 6.7, only user with `uid` can login.

```
Could not authorize you from LDAP because ldap account must provide a dn, uid and email address.
```

My LDAP section in `gitlab.yml`:

```yaml
  ldap:
    enabled: true
    host: "192.168.15.159"
    base: "ou=ad,dc=vc,dc=vn"
    port: 389
    uid: "cn"
    method: "plain" # "ssl" or "plain"
    bind_dn: "cn=anonymous,ou=ad,dc=vc,dc=vn"
    password: "password"
    allow_username_or_email_login: true
    user_filter: ""

```
I'm not sure if this is a new undocumented requirement or a bug?
