### ISSUE TITLE
Missing port number in "<img src=..." image paths

### ISSUE THREAD

**Issue by m-a-r-c-o** [gitlabhq/gitlabhq#8889]
I think that GitLab creates the wrong links to images (at least those in issue comments). I saw the following behavior today in my gitlab-development-kit environment:

The problem is that in the dev kit the gitlab page is served at port 3000 but the port number is not added to the img urls. Example:

![image](https://cloud.githubusercontent.com/assets/1237001/6428362/070a5e0e-bfa0-11e4-9b87-18b2fded4055.png)

Some days ago it was not an issue, all images were displayed. Now the images produce 404 respectively they are not displayed.

I assume that this is not a problem as long as gitlab is served at standard http (80) or https (443) ports but probably in all other cases.

**Comment by Razer6** [comment]
Thanks for that issue. @DouweM This might be related to the new uploads paths.

**Comment by DouweM** [comment]
@Razer6 thanks for alerting me, and @m-a-r-c-o thanks for reporting.

 I'll look into it tomorrow!

**Comment by DouweM** [comment]
@m-a-r-c-o Do you see this issue on master? It's working fine here:
![screen shot 2015-03-02 at 15 33 14](https://cloud.githubusercontent.com/assets/159434/6442616/7c1a9374-c0f1-11e4-8941-0ea172cebb0f.png)

That's with this (default) config:

```yaml
production: &base
  #
  # 1. GitLab app settings
  # ==========================

  ## GitLab settings
  gitlab:
    ## Web server settings (note: host is the FQDN, do not include http://)
    host: localhost
    port: 3000
    https: false # Set to true if using HTTPS, see installation.md#using-https for additional HTTPS configuration details
```
