### ISSUE TITLE
Can't clone after an upgrade

### ISSUE THREAD

**Issue by arnaud-zg** [gitlabhq/gitlabhq#9776]
Hello,
I just upgrade my server by this command `apt-get -y update && apt-get -y upgrade` and I have a feeling that break something on my Gitlab but I don't know what.

Everything works on the web interface, but when I want to clone a project it tell me that.
```
Cloning into `application`...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```
Thank you

**Comment by vsizov** [comment]
OS(Debian, Ubuntu)? Version (was, is)? Logs?

**Comment by arnaud-zg** [comment]
I'm on Debian GNU/Linux 7.8, I checked all logs but I don't really know which file I should take a look to find the bug.

**Comment by arnaud-zg** [comment]
And this is my `/var/opt/gitlab/gitlab-shell/config.yml`
```
# GitLab user. git by default
user: git

# Url to gitlab instance. Used for api calls. Should end with a slash.
gitlab_url: "http://localhost/"

http_settings:
#  user: someone
#  password: somepass
#  ca_file: /etc/ssl/cert.pem
#  ca_path: /etc/pki/tls/certs
  self_signed_cert: false

# Repositories path
# Give the canonicalized absolute pathname,
# REPOS_PATH MUST NOT CONTAIN ANY SYMLINK!!!
# Check twice that none of the components is a symlink, including "/home".
repos_path: "/home/git/repositories"

# File used as authorized_keys for gitlab user
auth_file: "/home/git/.ssh/authorized_keys"

# Redis settings used for pushing commit notices to gitlab
redis:
  bin: /usr/bin/redis-cli
  host: 127.0.0.1
  port: 6379
  socket: /var/run/redis/redis.sock
  namespace: resque:gitlab

# Log file.
# Default is gitlab-shell.log in the root directory.
# log_file: "/home/git/gitlab-shell/gitlab-shell.log"

# Log level. INFO by default
log_level: INFO

# Audit usernames.
# Set to true to see real usernames in the logs instead of key ids, which is easier to follow, but
# incurs an extra API call on every gitlab-shell command.
audit_usernames: false
```
