### ISSUE TITLE
git via ssh asking for password / authorized_keys text file not updating

### ISSUE THREAD

**Issue by eijoac** [gitlabhq/gitlabhq#9931]
GitLab Community Edition 8.2.2 08fae2f on redhat enterprise Linux 6.7 (omnibus installation). I also integrated LDAP to Gitlab and it works fine. Git via https works fine but git via ssh always asks for password (same thing if ssh -vT git@servername). Found out that the .ssh/authorized_keys text file is not updating (0 byte) when i add a public key using the web interface. Tried to rebuild the authorized_keys file using http://doc.gitlab.com/ce/raketasks/maintenance.html#rebuild-authorized_keys-file, but got the following error. Is this SSH problem related to LDAP setting? Any help.

```
sudo gitlab-rake gitlab:shell:setup
rake aborted!
Devise::OmniAuth::StrategyNotFound: Could not find a strategy with name `Ldapattributes'. Please ensure it is required or explicitly set it using the :strategy_class option.
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.2/lib/devise/omniauth/config.rb:40:in `autoload_strategy'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.2/lib/devise/omniauth/config.rb:25:in `strategy_class'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.2/lib/devise/rails.rb:22:in `block (2 levels) in <class:Engine>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.2/lib/devise/rails.rb:21:in `each'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.2/lib/devise/rails.rb:21:in `block in <class:Engine>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'
/opt/gitlab/embedded/service/gitlab-rails/config/environment.rb:5:in `<top (required)>'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:405:in `block in run_tasks_blocks'
Tasks: TOP => gitlab:shell:setup => environment
(See full trace by running task with --trace)
```

**Comment by stanhu** [comment]
That's odd. This suggests OmniAuth couldn't find the LDAP strategy, which should be named `LDAP`. How does your `/etc/gitlab/gitlab.rb` look with the omniauth config?

Can you run the following?

```
$ sudo gitlab-rails console
irb(main):002:0> OmniAuth.config.camelizations
=> {"oauth"=>"OAuth", "oauth2"=>"OAuth2", "github"=>"GitHub", "gitlab"=>"GitLab", "saml"=>"SAML", "ldap"=>"LDAP"}
```

**Comment by eijoac** [comment]
Hi Stan,

Thanks. A bit more info, the current GitLab Community Edition 8.2.2  08fae2f  installed is updated from an old version (just one release older). We also setup the https and we currently use a self-signed certificate.

The LDAP part of the /etc/gitlab/gitlab.rb looks like the following. The LDAP works fine. We didn't setup omniauth so the omniauth part in gitlab.rb is commented out as default.
```
gitlab_rails['ldap_enabled'] = true
gitlab_rails['ldap_servers'] = YAML.load <<-'EOS' # remember to close this block with 'EOS' below
main: # 'main' is the GitLab 'provider ID' of this LDAP server
  label: 'LDAP'
  host: 'registry.xyzcompany.com'
  port: 636
  uid: 'uid'
  method: 'ssl' # "tls" or "ssl" or "plain"
  bind_dn: 'cn=xyzcompanygitlab,ou=Service,dc=xyzcompany,dc=com'
  password: 'abcdefghijklmn'
  active_directory: false
  allow_username_or_email_login: false
  block_auto_created_users: false
  base: 'ou=People,dc=xyzcompany,dc=com'
  user_filter: ''

attributes:
  username: 'uid'
  email: ['mail', 'email']
  name: ['eduPersonPrincipalName','userPrincipalName']
```

When I run "sudo gitlab-rails console", I got error messages as following,
```
/opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.2/lib/devise/omniauth/config.rb:40:in `autoload_strategy': Could not find a strategy with name `Ldapattributes'. Please ensure it is required or explicitly set it using the :strategy_class option. (Devise::OmniAuth::StrategyNotFound)
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.2/lib/devise/omniauth/config.rb:25:in `strategy_class'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.2/lib/devise/rails.rb:22:in `block (2 levels) in <class:Engine>'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.2/lib/devise/rails.rb:21:in `each'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/devise-3.5.2/lib/devise/rails.rb:21:in `block in <class:Engine>'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /opt/gitlab/embedded/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
        from /opt/gitlab/embedded/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /opt/gitlab/embedded/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
        from /opt/gitlab/embedded/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /opt/gitlab/embedded/lib/ruby/2.1.0/tsort.rb:345:in `each'
        from /opt/gitlab/embedded/lib/ruby/2.1.0/tsort.rb:345:in `call'
        from /opt/gitlab/embedded/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
        from /opt/gitlab/embedded/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
        from /opt/gitlab/embedded/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'
        from /opt/gitlab/embedded/service/gitlab-rails/config/environment.rb:5:in `<top (required)>'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:147:in `require_application_and_environment!'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
        from /opt/gitlab/embedded/service/gem/ruby/2.1.0/gems/railties-4.1.12/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:8:in `require'
        from bin/rails:8:in `<main>'
```

Thanks again.

**Comment by stanhu** [comment]
I think I see the problem. I compared [this file](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/config/gitlab.yml.example) vs. the file generated via `/opt/gitlab/gitlab/gitlab-rails/etc/gitlab.yml`.

The `attributes` section should be indented one more block:

```
gitlab_rails['ldap_servers'] = YAML.load <<-'EOS' # remember to close this block with 'EOS' below
main: # 'main' is the GitLab 'provider ID' of this LDAP server
  label: 'LDAP'
  host: 'registry.xyzcompany.com'
  port: 636
  uid: 'uid'
  method: 'ssl' # "tls" or "ssl" or "plain"
  bind_dn: 'cn=xyzcompanygitlab,ou=Service,dc=xyzcompany,dc=com'
  password: 'abcdefghijklmn'
  active_directory: false
  allow_username_or_email_login: false
  block_auto_created_users: false
  base: 'ou=People,dc=xyzcompany,dc=com'
  user_filter: ''

  attributes:
    username: 'uid'
    email: ['mail', 'email']
    name: ['eduPersonPrincipalName','userPrincipalName']
```
