### ISSUE TITLE
Gitlab CE Tags triggering builds

### ISSUE THREAD

**Issue by Sladewill** [gitlabhq/gitlabhq#9945]
On version 8.3.2 gitlab CE when you create a tag on the `web UI` it does not trigger a build to gitlab ci this was working on the previous versions but it appears the recent update to the latest has this issue.

It does however work from a external interface such as sourcetree.

**Comment by atomaka** [comment]
I can confirm this issue.  Creating a tag via the web interface does not trigger a build.  However, if I create a local tag and then push to the remote, the build will run as expect.  The following is my `.gitlab-ci.yml file`

```
build:
  script:
    - docker build -t atomaka/link-share .
  except:
    - tags
deploy:
  script:
    - VERSION=$(git describe --tags)
    - docker build -t atomaka/link-share .
    - docker tag atomaka/link-share:latest example.com/atomaka/link-share:$VERSION
    - docker tag atomaka/link-share:latest example.com/atomaka/link-share:latest
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD -e me@example.com example.com
    - docker push example.com/atomaka/link-share
  only:
    - tags
```

This build file functioned as expected prior to upgrading so we are looking at a regression.
